### ISSUE TITLE
actually get mohammed uddin to contribute

### ISSUE THREAD

**Issue by anotherLostKitten** [jesings/multiperson-anacoluthon#28]

**Comment by muddint** [comment]
this seems difficult

**Comment by jesings** [comment]
We can find something not too terribly hard for you to do. Is it the fact that it is rust that makes it difficult @Trollicorn ?

**Comment by anotherLostKitten** [comment]
@Trollicorn you could start by reviewing prs

**Comment by muddint** [comment]
setup is done we're halfway there
